credentials:
  usernames:
    john_doe:
      email: john@acmecorp.com
      name: John Doe
      password: john123   # 👈 change THIS
      organization: org_acme
      role: employee

cookie:
  expiry_days: 30
  key: some_secret_key
  name: login_cookie

preauthorized:
  emails: []credentials:
  usernames:
    john_doe:
      email: john@acmecorp.com
      name: John Doe
      password: john123   # 👈 change THIS
      organization: org_acme
      role: employee

cookie:
  expiry_days: 30
  key: some_secret_key
  name: login_cookie

preauthorized:
  emails: []
